### ISSUE TITLE
arm64 architecture is missing for snap install

### ISSUE THREAD

**Issue by chrbayer** [dundee/gdu#9]
On a rasp pi 4 with arm64 architecture it is not possible to install gdu because only armhf builds are provided. Please provide arm64 builds as well :-)

Thank you very much in advance!

**Comment by dundee** [comment]
Released to latest/edge. Let me please know if it works fine. Thanks!

**Comment by chrbayer** [comment]
Thanks for the quick build!

Unfortunately the build does not work properly. After starting gdu . the output freezes without scanning, after that this error is shown:

```
Mo Jan 11 2021 00:19 (43.3C/1.36/1.65/1.66) [2612]% gdu .            
panic: interface conversion: interface {} is nil, not *analyze.File [recovered]
	panic: interface conversion: interface {} is nil, not *analyze.File

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0x400023a000)
	/root/go/pkg/mod/github.com/rivo/tview@v0.0.0-20201204190810-5406288b8e4e/application.go:243 +0x78
panic(0x553d60, 0x400054e0c0)
	/snap/go/6746/src/runtime/panic.go:969 +0x15c
github.com/dundee/gdu/cli.(*UI).fileItemSelected(0x4000232000, 0x0, 0x0)
	/build/gdu-disk-usage-analyzer/parts/gdu/build/cli/cli.go:299 +0xfc
github.com/dundee/gdu/cli.(*UI).keyPressed(0x4000232000, 0x400053c300, 0x400028fd08)
	/build/gdu-disk-usage-analyzer/parts/gdu/build/cli/cli.go:389 +0x1c4
github.com/rivo/tview.(*Application).Run(0x400023a000, 0x0, 0x0)
	/root/go/pkg/mod/github.com/rivo/tview@v0.0.0-20201204190810-5406288b8e4e/application.go:314 +0x698
github.com/dundee/gdu/cli.(*UI).StartUILoop(...)
	/build/gdu-disk-usage-analyzer/parts/gdu/build/cli/cli.go:207
main.main()
	/build/gdu-disk-usage-analyzer/parts/gdu/build/main.go:65 +0x454
```

**Comment by dundee** [comment]
Hm, sounds like some problem with the console interface. I have fixed build tag, could you try it again?

And maybe retest with https://github.com/dundee/gdu/releases/download/v2.2.0/gdu-linux-arm64.tgz ?

**Comment by chrbayer** [comment]
Thanks for working on this! The snap version doesn't work again, the downloaded file just works fine. So it looks like the Problem is inside the snap packaging...

**Comment by dundee** [comment]
I have modified the snap package, could you try it again?

**Comment by chrbayer** [comment]
It still does not work... It does not crash, but no files are scanned for my home directory... I can quit by pressing the q button.
If I try to scan /, it does something, /lib is scanned but all other directories get size 0.

**Comment by dundee** [comment]
Does it work if you pass no dir (for listing devices)? Or if you scan `/var/lib/snapd/hostfs`?

**Comment by chrbayer** [comment]
The last version I installed from snap was packed for core18. If I try gdu without arguments, I get an error about a missing permission (a missing snap permission?):

```
panic: open /proc/mounts: permission denied
```

Scanning `/var/lib/snapd/hostfs` doesn't find any files again...

**Comment by dundee** [comment]
I have published version 2.3.0 with core20 to edge and with core18 to stable. Could you try both?

They seem to be working both on amd64.

**Comment by chrbayer** [comment]
I tried both of them, both behave the same as the last version... Still some permissions missing....

**Comment by dundee** [comment]
I have added needed permissions, but manual review from snap team is required - https://dashboard.snapcraft.io/snaps/gdu-disk-usage-analyzer/revisions/126/

So stay tuned :)

**Comment by dundee** [comment]
Should be fixed now. See version 4.3.1 and README for install instructions. Thanks!

**Comment by chrbayer** [comment]
Hi, installed version 4.3.1 from snap edge channel followed instructions, but the two new commands fail:

```
sudo snap connect gdu-disk-usage-analyzer.gdu:mount-observe :mount-observe
Error: snap "gdu-disk-usage-analyzer.gdu" has no plug named "mount-observe"
snap connect gdu-disk-usage-analyzer.gdu:system-backup :system-backup
Error: snap "gdu-disk-usage-analyzer.gdu" has no plug named "system-backup"
```

**Comment by dundee** [comment]
That is strange. It works for me on Ubuntu 20.04. Just released to stable channel as well.

**Comment by chrbayer** [comment]
I investigated the problem: After checking all plugs in the snap, I noticed there is a typo in the readme file:

snap connect gdu-disk-usage-analyzer.gdu:mount-observe :mount-observe
snap connect gdu-disk-usage-analyzer.gdu:system-backup :system-backup

For the commands the name of the snap is not correct, it is extended by .gdu

After using the correct commands, its works as expected.

Thank you very much!

**Comment by dundee** [comment]
Oh my :rofl: 

I was checking the commands twice and still didn't notice this. 

Thank you!
